openapi: 3.1.0
info:
  title: NodeJS Template API
  version: 1.0.0
  description: API documentation for the Node.js template project

servers:
  - url: http://localhost:3000

paths:
  /health:
    $ref: './paths/health/health.yaml'
  /health/error:
    $ref: './paths/health/error.yaml'

components:
  schemas:
    HealthResponse:
      $ref: './components/schemas/health.schema.yaml'
    HealthErrorResponse:
      $ref: './components/schemas/error.schema.yaml'
  responses:
    SuccessResponse:
      $ref: './components/responses/success.response.yaml'
    ErrorResponse:
      $ref: './components/responses/error.response.yaml'
